### ISSUE TITLE
No such file or directory: 'datasets/Omni3D/SUNRGBD_test_novel.json'

### ISSUE THREAD

**Issue by YangHan-Morningstar** [UVA-Computer-Vision-Lab/ovmono3d#4]
Hi, I had download the Omni3D_json.zip and there are many {DatasetName}_{split}.json (e.g. nuScenes_train.json), but there are not {DatasetName}_{split}_{base or novel or all}.json, when I use the validation command, here it is: FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Omni3D/SUNRGBD_test_novel.json'. Could you tell me where I can download these json file? Thanks!

**Comment by YangHan-Morningstar** [comment]
And same error happened during the training process:
![image](https://github.com/user-attachments/assets/01532d42-04eb-49f9-a552-66c3d42debdc)

**Comment by yaojin17** [comment]
Thanks for pointing out this problem! I have updated the dataset. Running ```sh ./download_data.sh``` will download all the required dataset files.
